version: '2'

services:
  certbot:
    build: .
    container_name: certbot
    volumes:
      - certbot-data:/certs
      - letsencrypt-data:/etc/letsencrypt
    restart: always
    environment:
      - DOMAINS=domain1.com domain2.com
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - EMAIL=webmaster@domain1.com
      - CLOUDFLARE_TOKEN=
      - CONCAT=true
      - SEPARATE=true
      - LOG=true
volumes:
  certbot-data:
  letsencrypt-data:
